name: Build and Deploy to S3 the React App
on:
    release:
        types: [created,published]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Install packages
        run: npm install
      - name: Build the application
        run: npm build:dev
      - name: Test the application
        run: npm test
      - name: Publish package on NPM 📦
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      